### ISSUE TITLE
`pip install` failed on Python 3.12+

### ISSUE THREAD

**Issue by shi0rik0** [skvark/opencv-python#1059]
I'm trying to manually build a wheel from source. My Python version is 3.13. When I run `pip install .`, I see the following error:

```
      Traceback (most recent call last):
        File "C:\Users\anguu\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\anguu\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\anguu\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
        File "C:\Users\anguu\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
        File "C:\Users\anguu\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\anguu\AppData\Local\Temp\pip-build-env-jll306wz\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\anguu\AppData\Local\Temp\pip-build-env-jll306wz\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\anguu\AppData\Local\Temp\pip-build-env-jll306wz\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

I did some search and found that it may be due to the removal of deprecated `ImpImporter` since Python 3.12 (https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean).

One possible fix is to update `setuptools`, so I changed the build dependencies specified in `pyproject.toml` and it worked.

```toml
[build-system]
requires = [
  "cmake>=3.1",
  "numpy==1.13.3; python_version=='3.6' and platform_machine != 'aarch64' and platform_machine != 'arm64'",
  "numpy==1.17.0; python_version=='3.7' and platform_machine != 'aarch64' and platform_machine != 'arm64'",
  "numpy==1.17.5; python_version=='3.8' and platform_machine != 'aarch64' and platform_machine != 'arm64'",
  "numpy==1.19.3; python_version<'3.9' and sys_platform == 'linux' and platform_machine == 'aarch64'",
  "numpy==1.21.0; python_version<'3.9' and sys_platform == 'darwin' and platform_machine == 'arm64'",
  "numpy>=2.0.0;  python_version>='3.9'",
  "pip",
  "scikit-build>=0.14.0",
  "setuptools", # <----- I removed the version "==59.2.0"
]

```

However, changing the version of `setuptools` may cause unexpected affects. Could you please investigate this bug and publish an official fix?

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by patchmeifyoucan** [comment]
I am also interested in using OpenCV with Python 3.13, especially the free-threaded 3.13t builds. What is the current status of support and the general agenda to support the free-threaded builds?

**Comment by xbkaishui** [comment]
agree +1, any update on this

**Comment by cpatulea** [comment]
I was using Home Assistant + OpenCV last year. This year I updated OpenCV to the latest version, and got the surprise that they dropped OpenCV (https://github.com/home-assistant/core/issues/94617). The developers had tried to update OpenCV version during the Python 3.11 update, but failed and reverted (https://github.com/home-assistant/core/pull/91802). The state today is that Home Assistant uses Python 3.13, and the wheel build still fails with the 'pkgutil.ImpImporter' error. Repro in the Home Assistant build environment:

```
$ docker pull ghcr.io/home-assistant/wheels/amd64/musllinux_1_2/cp313:dev
$ docker run --rm --entrypoint="" -it ghcr.io/home-assistant/wheels/amd64/musllinux_1_2/cp313:dev bash
75c590f38fa7:/data# pip install opencv-python-headless
Collecting opencv-python-headless
  Downloading opencv-python-headless-4.10.0.84.tar.gz (95.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
        File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
        File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-1_kw6d26/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-1_kw6d26/overlay/lib/python3.13/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-1_kw6d26/overlay/lib/python3.13/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I used to have a very simple image processing script that reads from a phone camera, runs some simple OpenCV operations, and provides data to Home Assistant, and for now I don't see any way to get my script running working again.

**Comment by cpatulea** [comment]
This pull request looks related: https://github.com/opencv/opencv-python/pull/1061

**Comment by cpatulea** [comment]
More PR related to 3.12 / setuputils: https://github.com/opencv/opencv-python/pull/1012

**Comment by cpatulea** [comment]
And 3.12 related issue: https://github.com/opencv/opencv-python/issues/988

**Comment by asmorkalov** [comment]
Fixed in https://github.com/opencv/opencv-python/pull/1061

**Comment by cpatulea** [comment]
Confirming it built successfully, inside HomeAssistant Python 3.13 environment:

```
$ docker run --rm --entrypoint="" -it ghcr.io/home-assistant/wheels/amd64/musllinux_1_2/cp313:dev bash
ccda9f8c136b:/data# pip install opencv-python-headless
Collecting opencv-python-headless
  Downloading opencv-python-headless-4.11.0.86.tar.gz (95.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.21.2 in /usr/local/lib/python3.13/site-packages (from opencv-python-headless) (2.2.0)
Building wheels for collected packages: opencv-python-headless
  Building wheel for opencv-python-headless (pyproject.toml) ... done
  Created wheel for opencv-python-headless: filename=opencv_python_headless-4.11.0.86-cp313-cp313-linux_x86_64.whl size=31041885 sha256=66b23b933d36749e605120586d538ec464dfde5e710f02554ee5eac26c847d40
  Stored in directory: /tmp/pip-ephem-wheel-cache-gpkz3s8c/wheels/91/e4/cb/07f219c48753ca3e4e2248107107f1a0aec0d2b8553f21ecae
Successfully built opencv-python-headless
Installing collected packages: opencv-python-headless
Successfully installed opencv-python-headless-4.11.0.86
```
