### ISSUE TITLE
Module superres not available?

### ISSUE THREAD

**Issue by ryandsiskind** [skvark/opencv-python#155]
### Expected behaviour

```
>>> from cv2 import superres
```
no errors

### Actual behaviour

```
>>> from cv2 import superres
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'superres' from 'cv2.cv2' (/Users/zXXXXXX/.virtualenvs/cv-py3/lib/python3.7/site-packages/cv2/cv2.cpython-37m-darwin.so)
```

### Steps to reproduce
```
SuperResolution > pip uninstall opencv_contrib_python
Uninstalling opencv-contrib-python-3.4.4.19:
  Would remove:
    /Users/zXXXXXX/.virtualenvs/cv-py3/lib/python3.7/site-packages/cv2/*
    /Users/zXXXXXX/.virtualenvs/cv-py3/lib/python3.7/site-packages/opencv_contrib_python-3.4.4.19.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled opencv-contrib-python-3.4.4.19

SuperResolution > pip install opencv_contrib_python --no-cache-dir
Collecting opencv_contrib_python
  Downloading https://files.pythonhosted.org/packages/93/18/87865f32ea01c4d2f0671f8ecd97088b0440cd0b732f5f587a0f636fd2f4/opencv_contrib_python-3.4.4.19-cp37-cp37m-macosx_10_6_x86_64.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (54.3MB)
    100% |████████████████████████████████| 54.3MB 12.6MB/s 
Requirement already satisfied: numpy>=1.14.5 in /Users/zXXXXXX/.virtualenvs/cv-py3/lib/python3.7/site-packages (from opencv_contrib_python) (1.15.4)
Installing collected packages: opencv-contrib-python
Successfully installed opencv-contrib-python-3.4.4.19

SuperResolution > python
Python 3.7.1 (default, Nov  6 2018, 18:45:35) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> from cv2 import superres
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'superres' from 'cv2.cv2' (/Users/zXXXXXX/.virtualenvs/cv-py3/lib/python3.7/site-packages/cv2/cv2.cpython-37m-darwin.so)
```
- operating system
macOS High Sierra, build 10.13.6
Darwin 15.6.0 x86-64

- opencv-python version
```
>>> import cv2

>>> print(cv2.getBuildInformation())

General configuration for OpenCV 3.4.4 =====================================
  Version control:               3.4.4

  Extra modules:
    Location (extra):            /Users/travis/build/skvark/opencv-python/opencv_contrib/modules
    Version control (extra):     3.4.4

  Platform:
    Timestamp:                   2018-11-27T15:49:48Z
    Host:                        Darwin 15.6.0 x86_64
    CMake:                       3.6.1
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3 SSSE3
      requested:                 DETECT
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (4 files):          + SSE4_1
      SSE4_2 (1 files):          + SSE4_1 POPCNT SSE4_2
      FP16 (0 files):            + SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (5 files):             + SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (10 files):           + SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2

  C/C++:
    Built as dynamic libs?:      NO
    C++ Compiler:                /usr/local/opt/ccache/libexec/clang++  (ver 8.0.0.8000038)
    C++ flags (Release):         -stdlib=libc++   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -stdlib=libc++   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /usr/local/opt/ccache/libexec/clang
    C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      
    Linker flags (Debug):        
    ccache:                      YES
    Precompiled headers:         NO
    Extra dependencies:          -framework OpenCL /usr/local/lib/QtGui.framework /usr/local/lib/QtTest.framework /usr/local/lib/QtCore.framework avcodec avformat avutil swscale avresample -framework VideoDecodeAcceleration bz2 -framework Cocoa -framework Accelerate -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreVideo -framework QuartzCore
    3rdparty dependencies:       ittnotify libprotobuf libjpeg-turbo libwebp libpng libtiff libjasper IlmImf quirc zlib ippiw ippicv

  OpenCV modules:
    To be built:                 aruco bgsegm bioinspired calib3d ccalib core datasets dnn dnn_objdetect dpm face features2d flann fuzzy hfs highgui img_hash imgcodecs imgproc java_bindings_generator line_descriptor ml objdetect optflow phase_unwrapping photo plot python3 python_bindings_generator reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
    Disabled:                    world
    Disabled by dependency:      -
    Unavailable:                 cnn_3dobj cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv freetype hdf java js matlab ovis python2 sfm ts viz
    Applications:                -
    Documentation:               NO
    Non-free algorithms:         NO

  GUI: 
    QT:                          YES (ver 4.8.7 EDITION = OpenSource)
      QT OpenGL support:         NO
    Cocoa:                       YES
    VTK support:                 NO

  Media I/O: 
    ZLib:                        build (ver 1.2.11)
    JPEG:                        build-libjpeg-turbo (ver 1.5.3-62)
    WEBP:                        build (ver encoder: 0x020e)
    PNG:                         build (ver 1.6.35)
    TIFF:                        build (ver 42 - 4.0.9)
    JPEG 2000:                   build (ver 1.900.1)
    OpenEXR:                     build (ver 1.7.1)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES

  Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES
      avcodec:                   YES (ver 58.35.100)
      avformat:                  YES (ver 58.20.100)
      avutil:                    YES (ver 56.22.100)
      swscale:                   YES (ver 5.3.100)
      avresample:                YES (ver 4.0.0)
    GStreamer:                   NO
    AVFoundation:                YES

  Parallel framework:            GCD

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2019.0.0 Gold [2019.0.0]
           at:                   /Users/travis/build/skvark/opencv-python/_skbuild/macosx-10.6-intel-3.7/cmake-build/3rdparty/ippicv/ippicv_mac/icv
    Intel IPP IW:                sources (2019.0.0)
              at:                /Users/travis/build/skvark/opencv-python/_skbuild/macosx-10.6-intel-3.7/cmake-build/3rdparty/ippicv/ippicv_mac/iw
    Eigen:                       NO
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)

  OpenCL:                        YES (no extra features)
    Include path:                NO
    Link libraries:              -framework OpenCL

  Python 3:
    Interpreter:                 /Users/travis/build/skvark/opencv-python/venv/bin/python (ver 3.7)
    Libraries:                   /Library/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib (ver 3.7.0)
    numpy:                       /Users/travis/build/skvark/opencv-python/venv/lib/python3.7/site-packages/numpy/core/include (ver 1.14.5)
    packages path:               lib/python3.7/site-packages

  Python (for build):            /Users/travis/build/skvark/opencv-python/venv/bin/python

  Java:                          
    ant:                         NO
    JNI:                         /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/JavaVM.framework/Headers /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/JavaVM.framework/Headers /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/JavaVM.framework/Headers
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    /Users/travis/build/skvark/opencv-python/_skbuild/macosx-10.6-intel-3.7/cmake-install
-----------------------------------------------------------------
```

**Comment by skvark** [comment]
It looks like there are no Python binding generators for that module in OpenCV: https://docs.opencv.org/3.4.4/d7/d0a/group__superres.html

You could request or add them yourself to opencv contrib: https://github.com/opencv/opencv_contrib/issues
