### ISSUE TITLE
Conda - opencv-python

### ISSUE THREAD

**Issue by marcelotrevisani** [skvark/opencv-python#187]
Hi, 

I am trying to create a recipe for ``opencv-python`` to ``conda-forge``. 
I was wondering if it is possible to use an ``opencv`` which is already compiled, because ``conda-forge`` already have ``opencv`` in their repository.

One of the problems which I am facing is
```
Created temporary directory: /tmp/pip-ephem-wheel-cache-995flqoz
Created temporary directory: /tmp/pip-req-tracker-h92jm1z_
Created requirements tracker '/tmp/pip-req-tracker-h92jm1z_'
Created temporary directory: /tmp/pip-install-mgyaa6s3
Processing $SRC_DIR
  Created temporary directory: /tmp/pip-req-build-va92foo9
  Added file://$SRC_DIR to build tracker '/tmp/pip-req-tracker-h92jm1z_'
    Running setup.py (path:/tmp/pip-req-build-va92foo9/setup.py) egg_info for package from file://$SRC_DIR
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-va92foo9/setup.py", line 382, in <module>
        main()
      File "/tmp/pip-req-build-va92foo9/setup.py", line 62, in main
        package_version = get_opencv_version()
      File "/tmp/pip-req-build-va92foo9/setup.py", line 336, in get_opencv_version
        runpy.run_path("find_version.py")
      File "$PREFIX/lib/python3.7/runpy.py", line 263, in run_path
        pkg_name=pkg_name, script_name=fname)
      File "$PREFIX/lib/python3.7/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "$PREFIX/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "find_version.py", line 9, in <module>
        with open(version_file_path, 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'opencv/modules/core/include/opencv2/core/version.hpp'
Cleaning up...
  Removing source in /tmp/pip-req-build-va92foo9
Removed file://$SRC_DIR from build tracker '/tmp/pip-req-tracker-h92jm1z_'
Removed build tracker '/tmp/pip-req-tracker-h92jm1z_'
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-va92foo9/
Exception information:
Traceback (most recent call last):
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 349, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 158, in prep_for_dist
    self.req.prepare_metadata()
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 530, in prepare_metadata
    self.run_egg_info()
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 609, in run_egg_info
    command_desc='python setup.py egg_info')
  File "$PREFIX/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-va92foo9/
Traceback (most recent call last):
  File "/home/marcelotrevisani/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/marcelotrevisani/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/home/marcelotrevisani/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/home/marcelotrevisani/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/marcelotrevisani/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/home/marcelotrevisani/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 1477, in build
    cwd=src_dir, stats=build_stats)
  File "/home/marcelotrevisani/miniconda3/lib/python3.7/site-packages/conda_build/utils.py", line 374, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/marcelotrevisani/miniconda3/lib/python3.7/site-packages/conda_build/utils.py", line 354, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/marcelotrevisani/miniconda3/conda-bld/opencv-python_1554905194603/work/conda_build.sh']' returned non-zero exit status 1.

```

**Comment by skvark** [comment]
I don't exactly understand what you are doing (there is already a OpenCV recipe in conda-forge, what's the benefit in creating another one? https://github.com/conda-forge/opencv-feedstock), but as the error says ``No matching distribution found for scikit-build`` which will lead to ``ValueError: not enough values to unpack (expected 1, got 0)`` because the list comprehension returns an empty list since ``scikit-build`` was not installed. 

If you are trying to use precompiled binaries, then you don't really need ``scikit-build`` or most of the code in the ``setup.py`` file, do you? Just copy the binaries to ``cv2`` folder and make sure they are included in ``package_data``.

**Comment by marcelotrevisani** [comment]
Yes, sorry, I sent the wrong error but I fixed it

I was trying to create a recipe for ``opencv-python``
I was lead by a mistake in my project which is using ``opencv-python``. However, now I see that is similar as ``opencv`` in ``conda-forge``. Sorry, about that
