### ISSUE TITLE
Cannot load a .tiff file with opencv

### ISSUE THREAD

**Issue by bjce** [skvark/opencv-python#220]
I'm trying to show an image with openCV 4.1 in python 3.7 with the following code:
```
import cv2
img_path = 'Path/to/image.tiff'
img = cv2.imread(img_path)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
```
But it gives me the following error message:
```
error: OpenCV(4.1.0) /tmp/opencv-20190505-12101-14vk1fh/opencv-4.1.0/modules/highgui/src/window.cpp:352: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'
```
What am I doing wrong?

**EDIT**:

It doesn't seem to be a permission problem or that the file doesn't exist because I can display the image using the following code with matplotlib
```
import matplotlib.pyplot as plt
img_path = 'Path/to/image.tiff'
img = plt.imread(img_path)
fig = plt.figure(0)
plt.imshow(img)
plt.show()
```

**EDIT 2**:

Trying `tifffile` package
```
import tifffile as tiff
a = tiff.imread(img_path)
a.shape
```

I get now the following error message: 
```
Traceback (most recent call last):
  File "opencv_script.py", line 16, in <module>
    a = tiff.imread(img_path)
  File "/Users/mymac/miniconda3/envs/pyimageprocessing/lib/python3.7/site-packages/tifffile/tifffile.py", line 720, in imread
    return tif.asarray(**kwargs)
  File "/Users/mymac/miniconda3/envs/pyimageprocessing/lib/python3.7/site-packages/tifffile/tifffile.py", line 2405, in asarray
    maxworkers=maxworkers)
  File "/Users/mymac/miniconda3/envs/pyimageprocessing/lib/python3.7/site-packages/tifffile/tifffile.py", line 4539, in asarray
    strip = unpack(strip)
  File "/Users/mymac/miniconda3/envs/pyimageprocessing/lib/python3.7/site-packages/tifffile/tifffile.py", line 4491, in unpack
    runlen)
  File "/Users/mymac/miniconda3/envs/pyimageprocessing/lib/python3.7/site-packages/tifffile/tifffile.py", line 10306, in packints_decode
    % (numbits, numpy.dtype(dtype)))
NotImplementedError: unpacking 12-bit integers to uint16 not supported
```

Trying `libdif` package:

```
import libtiff
# img_path = "/Users/mymac/Documents/research/In-Vitro_AK_Studie/boarder_tracking_py/line.jpg"
img_path = '/Users/mymac/Documents/research/In-Vitro_AK_Studie/boarder_tracking_py/Camera No.1_C001H001S0001000561.tif'
# img_path_save = '/Users/mymac/Documents/research/In-Vitro_AK_Studie/boarder_tracking_py/modif.tif'
# img = plt.imread(img_path)
# threshold the image
# img.shape
# fig = plt.figure(0)
# plt.imshow(img)
# plt.show()

tif = libtiff.TIFF.open(img_path)
im = tif.read_image()
```
I get: 
```
Traceback (most recent call last):
  File "opencv_script.py", line 18, in <module>
    im = tif.read_image()
  File "/Users/mymac/miniconda3/envs/pyimageprocessing/lib/python3.7/site-packages/libtiff/libtiff_ctypes.py", line 552, in read_image
    typ = self.get_numpy_type(bits, sample_format)
  File "/Users/mymac/miniconda3/envs/pyimageprocessing/lib/python3.7/site-packages/libtiff/libtiff_ctypes.py", line 509, in get_numpy_type
    raise NotImplementedError("bits = {0:d}".format(bits))
NotImplementedError: bits = 12
```
I then installed `imagecodecs-lite` but got this error message:

```
Traceback (most recent call last):
  File "opencv_script.py", line 19, in <module>
    im = tif.read_image()
  File "/Users/mymac/miniconda3/envs/pyimageprocessing/lib/python3.7/site-packages/libtiff/libtiff_ctypes.py", line 552, in read_image
    typ = self.get_numpy_type(bits, sample_format)
  File "/Users/mymac/miniconda3/envs/pyimageprocessing/lib/python3.7/site-packages/libtiff/libtiff_ctypes.py", line 509, in get_numpy_type
    raise NotImplementedError("bits = {0:d}".format(bits))
NotImplementedError: bits = 1
```

**Comment by skvark** [comment]
I don't what's the actual problem, but your ``img`` variable is empty and thus OpenCV throws this error (your image size is 0 x 0):

 ``error: OpenCV(4.1.0) /tmp/opencv-20190505-12101-14vk1fh/opencv-4.1.0/modules/highgui/src/window.cpp:352: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'``.

OpenCV (more precisely the underlying libtiff library) can't probably handle the tiff file correctly.

You should open an issue to OpenCV repository https://github.com/opencv/opencv or to https://answers.opencv.org/questions/. This repository contains just some automated scripts to generate pre-built OpenCV packages for Python.

**Comment by joaquinmura** [comment]
I got exactly the same issue:
```python
import os
import cv2

file_ = '01_manual1.tif'
if os.path.isfile(file_) : print(file_, " exists!") # is ok!!
img = cv2.imread(file_) 
print(img) # None
```
which produces an empty matrix. However, this works perfectly
```python
import matplotlib.pyplot as plt
img = plt.imread(file_)
```
and then I continue using the same opencv code (`cv2.imshow`,`cv2.resize`,`cv2.threshold`,etc).
Even more strange, with some other set of .tif images, I found no issues (gray or color). 

Maybe it is related to this: https://github.com/opencv/opencv/issues/17054
but I don't know how to check that from Python, and even does not seem to be solved within opencv. Attached you'll find one of those files if someone finds the cure.

[01_manual1.zip](https://github.com/skvark/opencv-python/files/5758258/01_manual1.zip)

**Comment by cgohlke** [comment]
`01_manual1.tif` is actually a GIF image:

```Python
>>> python -c"print(open('01_manual1.tif', 'rb').read(5))"
b'GIF89'
```

**Comment by joaquinmura** [comment]
> `01_manual1.tif` is actually a GIF image:
> 
> ```python
> >>> python -c"print(open('01_manual1.tif', 'rb').read(5))"
> b'GIF89'
> ```

Thank you, @cgohlke. This story's moral is that we need to check TIF files before and convert them to another format allowed by OpenCV, if necessary.
