### ISSUE TITLE
DLL Dependencies fail in virtual environment

### ISSUE THREAD

**Issue by FlorinSchwappach** [skvark/opencv-python#27]
First of all, thanks a lot for the work on this distribution, it has been very helpful so far! 

I have been running opencv-python on a win10/x64 device with python 2.7 and 3.6 successfully. Now, I wanted to use it on a new device, also win10/x64. I've installed it through the PyCharm-GUI, in a fresh virtualenv with python 3.6. Same simple process as my other device. 

When I want to import cv2, I get the error "ImportError: DLL load failed (...)". Using find_module(), the correct path to the folder cv2 in site-packages is returned. But during interpretation of __init__.py, the "from . import cv2" line fails.

I have checked dependencies with dependencywalker, and I have scanned for broken dlls. I have all Redistributable packages since 2010 installed (2010, 2012, 2013, 2015). I also reinstalled all those once already.

I have tried copying around cv2.pyd. At one point, the error message changed: When I used a x86 file, I got the (expected) error message "Not a win32 ...". So the pyd is found by python, but for some reason, loading it fails.

A seemingly identical setup (at least concerning the virtualenv) works on one device and not on another. Do you have a clue what could be missing?

**Comment by skvark** [comment]
Does the import work in virtual environments on that other device? You could try just pure python virtual env (or just global installation) on command line without the PyCharm. If it works, PyCharm does something differently.

Also check that you have all the latest Windows updates installed.

**Comment by skvark** [comment]
Closing this for inactivity. Please reopen if this is still a problem for you or if you can provide more details.

**Comment by roachsinai** [comment]
DLL load failed error when importing cv2 on Windows10 + Python3.7. A method to solve the problem is install `opencv-contrib-python`. I installed by pip `pip install opencv-contrib-python`, find the solution from [here](https://stackoverflow.com/a/48414507/6074780).

**Comment by Yajan** [comment]
I am getting import error in Windows 10, Python 3.5.4 and Virtual Environment 


`ActivePython 3.5.4.3504 (ActiveState Software Inc.) based on
Python 3.5.4 (default, Dec 15 2017, 14:24:56) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Yajana\Documents\Python\mechine_learning\env\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: DLL load failed: The specified module could not be found.`
