### ISSUE TITLE
how can i build with ffmpeg Link library

### ISSUE THREAD

**Issue by GlassyWing** [skvark/opencv-python#329]
I build opencv-python with quay.io/skvark/manylinux1_x86_64, which the ffmpeg has been installed. But when i install the build whl in Ubuntu18 which has not insall ffmpeg, then the error happen 

```
root@5cf8440f30c1:/workspace# python -c "import cv2;print(cv2.getBuildInformation())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libavcodec.so.58: cannot open shared object file: No such file or directory
```

seems like the build whl not contains ffmpeg lib, how can i add it.

**Comment by skvark** [comment]
By default Linux and macOS wheels work only on the machine on which they were built. To fix this, you must run Auditwheel (https://github.com/pypa/auditwheel) for the wheel after the build while you are in the Docker image.

**Comment by GlassyWing** [comment]
> By default Linux and macOS wheels work only on the machine on which they were built. To fix this, you must run Auditwheel (https://github.com/pypa/auditwheel) for the wheel after the build while you are in the Docker image.

thanks for answer, i'll try it.

**Comment by GlassyWing** [comment]
with run `auditwheel show dist/opencv_python-4.2.0+f19d0ae-cp36-cp36m-linux_x86_64.whl `:

```
[root@a830d4f4d514 opencv-python-4.2.0]# auditwheel show dist/opencv_python-4.2.0+f19d0ae-cp36-cp36m-linux_x86_64.whl 

opencv_python-4.2.0+f19d0ae-cp36-cp36m-linux_x86_64.whl is consistent
with the following platform tag: "linux_x86_64".

The wheel references external versioned symbols in these system-
provided shared libraries: librt.so.1 with versions {'GLIBC_2.2.5'},
libswscale.so.5 with versions {'LIBSWSCALE_5'}, libgcc_s.so.1 with
versions {'GCC_4.0.0', 'GCC_3.0'}, libavutil.so.56 with versions
{'LIBAVUTIL_56'}, libavcodec.so.58 with versions {'LIBAVCODEC_58'},
libpthread.so.0 with versions {'GLIBC_2.3.2', 'GLIBC_2.2.5'},
libz.so.1 with versions {'ZLIB_1.2.0.2', 'ZLIB_1.2.0',
'ZLIB_1.2.3.4'}, libm.so.6 with versions {'GLIBC_2.2.5'}, libc.so.6
with versions {'GLIBC_2.3.4', 'GLIBC_2.3', 'GLIBC_2.17',
'GLIBC_2.3.2', 'GLIBC_2.16', 'GLIBC_2.4', 'GLIBC_2.7', 'GLIBC_2.14',
'GLIBC_2.2.5'}, libavformat.so.58 with versions {'LIBAVFORMAT_58'},
libdl.so.2 with versions {'GLIBC_2.2.5'}, libstdc++.so.6 with versions
{'GLIBCXX_3.4.18', 'GLIBCXX_3.4.11', 'GLIBCXX_3.4.14', 'GLIBCXX_3.4',
'GLIBCXX_3.4.9', 'CXXABI_1.3.3', 'GLIBCXX_3.4.19', 'GLIBCXX_3.4.15',
'CXXABI_1.3', 'CXXABI_1.3.5'}, libcrypto.so.1.1 with versions
{'OPENSSL_1_1_0f', 'OPENSSL_1_1_0', 'OPENSSL_1_1_0d',
'OPENSSL_1_1_0i', 'OPENSSL_1_1_1'}, libswresample.so.3 with versions
{'LIBSWRESAMPLE_3'}, libssl.so.1.1 with versions {'OPENSSL_1_1_0'}

This constrains the platform tag to "manylinux2014_x86_64". In order
to achieve a more compatible tag, you would need to recompile a new
wheel from source on a system with earlier versions of these
libraries, such as a recent manylinux image.
```
seems like not found those libs, while libs is here:
```
[root@a830d4f4d514 opencv-python-4.2.0]# ls ~/ffmpeg_build/lib/
engines-1.1              libavdevice.so           libavfilter.so.7.77.101   libavutil.so            libssl.a            libswresample.so.3.6.100  libvpx.so
libavcodec.a             libavdevice.so.58        libavformat.a             libavutil.so.56         libssl.so           libswscale.a              libvpx.so.6
libavcodec.so            libavdevice.so.58.9.103  libavformat.so            libavutil.so.56.42.102  libssl.so.1.1       libswscale.so             libvpx.so.6.2
libavcodec.so.58         libavfilter.a            libavformat.so.58         libcrypto.a             libswresample.a     libswscale.so.5           libvpx.so.6.2.0
libavcodec.so.58.77.101  libavfilter.so           libavformat.so.58.42.100  libcrypto.so            libswresample.so    libswscale.so.5.6.101     libyasm.a
libavdevice.a            libavfilter.so.7         libavutil.a               libcrypto.so.1.1        libswresample.so.3  libvpx.a                  pkgconfig
```
How to fix it

**Comment by skvark** [comment]
I don't understand? ``auditwheel repair whl_file_name.whl`` will produce new file which you can install.

**Comment by GlassyWing** [comment]
> I don't understand? `auditwheel repair whl_file_name.whl` will produce new file which you can install.

Sorry i didn't realize i used a different command. Succeeded like this, thank you
