### ISSUE TITLE
Unable to build on RHEL7

### ISSUE THREAD

**Issue by tedski** [skvark/opencv-python#367]
### Expected behaviour

Following the manual build process to build on RHEL7 should work as documented.

### Actual behaviour

Build fails with a failure related to `opencv-430.jar`.

```
  [ 98%] Built target opencv_java_jar_source_copy
  Scanning dependencies of target opencv_java_jar
  [ 98%] Generating opencv-430.jar
  Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
  Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0
  Buildfile: build.xml

  jar:
      [javac] Compiling 125 source files to /tmp/pip-req-build-8ts0bteb/_skbuild/linux-x86_64-3.7/cmake-build/modules/java/jar/opencv/build/classes
        [jar] Building jar: /tmp/pip-req-build-8ts0bteb/_skbuild/linux-x86_64-3.7/cmake-build/bin/opencv-430.jar
  Target 'jar' failed with message 'Problem creating jar: /tmp/pip-req-build-8ts0bteb/_skbuild/linux-x86_64-3.7/cmake-build/bin/opencv-430.jar (No such file or directory) (and the archive is probably corrupt but I could not delete it)'.

  BUILD FAILED
  /tmp/pip-req-build-8ts0bteb/_skbuild/linux-x86_64-3.7/cmake-build/modules/java/jar/opencv/build.xml:18: Problem creating jar: /tmp/pip-req-build-8ts0bteb/_skbuild/linux-x86_64-3.7/cmake-build/bin/opencv-430.jar (No such file or directory) (and the archive is probably corrupt but I could not delete it)

  Total time: 2 seconds
  gmake[2]: *** [CMakeFiles/dephelper/opencv_java_jar] Error 1
  gmake[1]: *** [modules/java/jar/CMakeFiles/opencv_java_jar.dir/all] Error 2
  gmake: *** [all] Error 2
    File "/tmp/pip-build-env-6z50yb3j/overlay/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 589, in setup
      cmkr.make(make_args, env=env)
    File "/tmp/pip-build-env-6z50yb3j/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 507, in make
      os.path.abspath(CMAKE_BUILD_DIR())))
```

### Steps to reproduce

- example code
```
$ git clone --recursive https://github.com/skvark/opencv-python.git
$ cd opencv-python
$ python3 -m venv ~/venvs/opencv/
$ . ~/venvs/opencv/bin/activate
$ pip install --upgrade pip
$ pip install scikit-build
[SNIP]
Successfully installed distro-1.5.0 packaging-20.4 pyparsing-2.4.7 scikit-build-0.11.1 six-1.15.0 wheel-0.34.2
$ pip wheel . --verbose
[SNIP]
  [ 98%] Built target opencv_java_jar_source_copy
  Scanning dependencies of target opencv_java_jar
  [ 98%] Generating opencv-430.jar
  Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
  Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0
  Buildfile: build.xml

  jar:
      [javac] Compiling 125 source files to /tmp/pip-req-build-x6z899pg/_skbuild/linux-x86_64-3.6/cmake-build/modules/java/jar/opencv/build/classes
        [jar] Building jar: /tmp/pip-req-build-x6z899pg/_skbuild/linux-x86_64-3.6/cmake-build/bin/opencv-430.jar
  Target 'jar' failed with message 'Problem creating jar: /tmp/pip-req-build-x6z899pg/_skbuild/linux-x86_64-3.6/cmake-build/bin/opencv-430.jar (No such file or directory) (and the archive is probably corrupt but I could not delete it)'.

  BUILD FAILED
  /tmp/pip-req-build-x6z899pg/_skbuild/linux-x86_64-3.6/cmake-build/modules/java/jar/opencv/build.xml:18: Problem creating jar: /tmp/pip-req-build-x6z899pg/_skbuild/linux-x86_64-3.6/cmake-build/bin/opencv-430.jar (No such file or directory) (and the archive is probably corrupt but I could not delete it)

  Total time: 2 seconds
  gmake[2]: *** [CMakeFiles/dephelper/opencv_java_jar] Error 1
  gmake[1]: *** [modules/java/jar/CMakeFiles/opencv_java_jar.dir/all] Error 2
  gmake: *** [all] Error 2
    File "/tmp/pip-build-env-83qe3o1u/overlay/lib/python3.6/site-packages/skbuild/setuptools_wrap.py", line 589, in setup
      cmkr.make(make_args, env=env)
    File "/tmp/pip-build-env-83qe3o1u/overlay/lib/python3.6/site-packages/skbuild/cmaker.py", line 507, in make
      os.path.abspath(CMAKE_BUILD_DIR())))


  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying "Unix Makefiles" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Unix Makefiles" generator - success
  --------------------------------------------------------------------------------

  Configuring Project
    Working directory:
      /tmp/pip-req-build-x6z899pg/_skbuild/linux-x86_64-3.6/cmake-build
    Command:
      cmake /tmp/pip-req-build-x6z899pg/opencv -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-req-build-x6z899pg/_skbuild/linux-x86_64-3.6/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/home/tstrzalk/venvs/opencv/bin/python3 -DPYTHON_VERSION_STRING:STRING=3.6.8 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.6m -DPYTHON_LIBRARY:FILEPATH=libpython3.6m.a -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-83qe3o1u/overlay/lib/python3.6/site-packages/skbuild/resources/cmake -DPYTHON3_EXECUTABLE=/home/tstrzalk/venvs/opencv/bin/python3 -DPYTHON3_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON3_LIBRARY=libpython3.6m.a -DBUILD_opencv_python3=ON -DBUILD_opencv_python2=OFF -DOPENCV_SKIP_PYTHON_LOADER=ON -DOPENCV_PYTHON3_INSTALL_PATH=python -DINSTALL_CREATE_DISTRIB=ON -DBUILD_opencv_apps=OFF -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_DOCS=OFF -DWITH_WIN32UI=OFF -DWITH_QT=OFF -DWITH_GTK=OFF -DCMAKE_BUILD_TYPE:STRING=Release

  Traceback (most recent call last):

  An error occurred while building with CMake.
    Command:
      cmake --build . --target install --config Release --
    Source directory:
      /tmp/pip-req-build-x6z899pg
    Working directory:
      /tmp/pip-req-build-x6z899pg/_skbuild/linux-x86_64-3.6/cmake-build
  Please see CMake's output for more information.
  Building wheel for opencv-python-headless (PEP 517) ... error
  ERROR: Failed building wheel for opencv-python-headless
Failed to build opencv-python-headless
ERROR: Failed to build one or more wheels
Exception information:
Traceback (most recent call last):
  File "/home/tstrzalk/venvs/opencv/lib64/python3.6/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/home/tstrzalk/venvs/opencv/lib64/python3.6/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/tstrzalk/venvs/opencv/lib64/python3.6/site-packages/pip/_internal/commands/wheel.py", line 185, in run
    "Failed to build one or more wheels"
pip._internal.exceptions.CommandError: Failed to build one or more wheels
Removed build tracker: '/tmp/pip-req-tracker-mhhv75kz'
```

- operating system
Red Hat Enterprise Linux Workstation release 7.6 (Maipo)

- architecture (e.g. x86)
x86_64

- opencv-python version
master

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by tedski** [comment]
This is an issue with the virtual environment.  I cannot reproduce this outside of the virtual environment, therefore I cannot reliably say this is an issue with opencv-python.  I believe this is an issue with adding some FindPython hints to CMAKE_ARGS in order to properly build.

**Comment by skvark** [comment]
It looks like OpenCV's Cmake script found some Java on your machine but failed to compile the java wrapper and failed the whole build. You could disable java via cmake args, I'll see if it makes sense to disable it in setup.py directly.

**Comment by tedski** [comment]
One thing I observed that was interesting and may be useful to you is that when building `opencv-python` using `pip wheel .`, the jar directory (`/tmp/pip-req-build-x6z899pg/_skbuild/linux-x86_64-3.6/cmake-build/bin/` in this issue) was not created.  However, when building the upstream `opencv` repo it was.  As a workaround during investigation, I patched one of the CMake files as so:

```
diff --git a/modules/java/jar/CMakeLists.txt b/modules/java/jar/CMakeLists.txt
index 33817bcc62..f302d46ca1 100644
--- a/modules/java/jar/CMakeLists.txt
+++ b/modules/java/jar/CMakeLists.txt
@@ -9,6 +9,7 @@ file(MAKE_DIRECTORY "${OPENCV_JAVA_DIR}/build/classes")
 set(java_src_dir "${OPENCV_JAVA_DIR}/java")
 file(MAKE_DIRECTORY "${java_src_dir}")

+file(MAKE_DIRECTORY "${OpenCV_BINARY_DIR}/bin")
 set(JAR_NAME opencv-${OPENCV_JAVA_LIB_NAME_SUFFIX}.jar)
 set(OPENCV_JAR_FILE "${OpenCV_BINARY_DIR}/bin/${JAR_NAME}" CACHE INTERNAL "")
```

This worked around the jar building issue, but it seems odd that I would have this issue and others wouldn't.

**Comment by tedski** [comment]
I tried disabling java and I have a new flavor of error:

```
$ echo $CMAKE_ARGS
-DBUILD_opencv_java=OFF
$ echo $ENABLE_HEADLESS
1
$ python3 setup.py sdist --formats=gztar
[SNIP]
$ pip install dist/opencv-python-headless-4.3.0+914404d.tar.gz
[SNIP]
Successfully built opencv-python-headless
Installing collected packages: opencv-python-headless
  Attempting uninstall: opencv-python-headless
    Found existing installation: opencv-python-headless 4.3.0+914404d
    Uninstalling opencv-python-headless-4.3.0+914404d:
      Created temporary directory: /home/tstrzalk/venvs/opencv/lib/python3.7/site-packages/~v2
      Removing file or directory /home/tstrzalk/venvs/opencv/lib/python3.7/site-packages/cv2/
      Created temporary directory: /home/tstrzalk/venvs/opencv/lib/python3.7/site-packages/~pencv_python_headless-4.3.0+914404d.dist-info
      Removing file or directory /home/tstrzalk/venvs/opencv/lib/python3.7/site-packages/opencv_python_headless-4.3.0+914404d.dist-info/
      Successfully uninstalled opencv-python-headless-4.3.0+914404d

Successfully installed opencv-python-headless-4.3.0+914404d
```

Seems like it worked, but I get an error on import:

```
>>> import cv2
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-c8ec22b3e787> in <module>()
----> 1 import cv2

~/src/opencv-python/cv2/__init__.py in <module>()
      3 import sys
      4
----> 5 from .cv2 import *
      6 from .data import *
      7

ModuleNotFoundError: No module named 'cv2.cv2'
```

**Comment by skvark** [comment]
The jar directory was not probably created because the we generate here only the Python bindings, nothing else.

The other issue you are having is caused by the fact that you are trying to import the package in the same directory where there original sources are (note the script path). Python always searches for packages from the current directory first and after that from the environment. Just go to some other directory and try again.

**Comment by tedski** [comment]
🤦 That's right.  I got lost in the weeds there.  Building without java enabled worked well.
