### ISSUE TITLE
"BackendUnavailable" error on install

### ISSUE THREAD

**Issue by LukeAI** [skvark/opencv-python#374]
Using pip 20.2.2, Python 2.7.12, Ubuntu 16.04, virtual environment

`pip install opencv-python==4.3.0.38`

Same error with 3.4.10.37 - so maybe related to this? https://github.com/skvark/opencv-python/issues/46#issuecomment-671063835

No error with 4.0.1.24

gives a BackendUnavailable error. This doesn't happen with other version of opencv installed in the same way inscluding 4.2.0

```
(aios-env) luke@AIDlaptop2:~/projects/AQC_CAS$ pip -V
pip 20.2.2 from /home/luke/projects/AQC_CAS/devel/aios-env/lib/python2.7/site-packages/pip (python 2.7)
(aios-env) luke@AIDlaptop2:~/projects/AQC_CAS$ pip install opencv-python==4.3.0.38
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting opencv-python==4.3.0.38
  Using cached opencv-python-4.3.0.38.tar.gz (88.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/home/luke/projects/AQC_CAS/devel/aios-env/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/home/luke/projects/AQC_CAS/devel/aios-env/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/luke/projects/AQC_CAS/devel/aios-env/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 325, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/luke/projects/AQC_CAS/devel/aios-env/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/luke/projects/AQC_CAS/devel/aios-env/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/luke/projects/AQC_CAS/devel/aios-env/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/luke/projects/AQC_CAS/devel/aios-env/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 483, in prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/home/luke/projects/AQC_CAS/devel/aios-env/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/luke/projects/AQC_CAS/devel/aios-env/lib/python2.7/site-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/home/luke/projects/AQC_CAS/devel/aios-env/lib/python2.7/site-packages/pip/_internal/distributions/sdist.py", line 96, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/home/luke/projects/AQC_CAS/devel/aios-env/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 161, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/home/luke/projects/AQC_CAS/devel/aios-env/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 265, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
BackendUnavailable
```

**Comment by skvark** [comment]
This project dropped Python 2.7 support earlier this year. The notice about this was pinned in this repository since 2018: https://github.com/skvark/opencv-python/issues/152

It's also clearly written in the 4.2.0.34 release notes: https://github.com/skvark/opencv-python/releases/tag/34

It's also written in the README: https://github.com/skvark/opencv-python#supported-python-versions

If you insist on using Python 2.7, then you are stuck with the latest supported release which is 4.2.0.32.

Please update to Python 3.8 and you can enjoy all the latest OpenCV features.
