### ISSUE TITLE
Unable to install v4.3.0.38 for python 2.7.17

### ISSUE THREAD

**Issue by kokkalisko** [skvark/opencv-python#379]
### Bug

Unable to install `opencv-python` version 4.3.0.38 for python 2.7.17 and pip version 20.2.2
(able to install version  4.2.0.32)

```
C:\Windows\System32>python -m pip install -U opencv-python
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting opencv-python
  Using cached opencv-python-4.3.0.38.tar.gz (88.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Python27\python.exe' 'C:\Python27\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'c:\users\kokkko\appdata\local\temp\tmp72km80'
       cwd: c:\users\kokkko\appdata\local\temp\pip-install-hwqqzy\opencv-python
  Complete output (22 lines):
  Traceback (most recent call last):
    File "C:\Python27\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "C:\Python27\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Python27\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "c:\users\kokkko\appdata\local\temp\pip-build-env-co1owf\overlay\Lib\site-packages\setuptools\build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "c:\users\kokkko\appdata\local\temp\pip-build-env-co1owf\overlay\Lib\site-packages\setuptools\build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "c:\users\kokkko\appdata\local\temp\pip-build-env-co1owf\overlay\Lib\site-packages\setuptools\build_meta.py", line 243, in run_setup
      self).run_setup(setup_script=setup_script)
    File "c:\users\kokkko\appdata\local\temp\pip-build-env-co1owf\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 448, in <module>
      main()
    File "setup.py", line 99, in main
      % {"ext": re.escape(sysconfig.get_config_var("EXT_SUFFIX"))}
    File "C:\Python27\lib\re.py", line 210, in escape
      s = list(pattern)
  TypeError: 'NoneType' object is not iterable
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Python27\python.exe' 'C:\Python27\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'c:\users\kokkko\appdata\local\temp\tmp72km80' Check the logs for full command output.
```

### Steps to reproduce

python -m pip install -U opencv-python==4.3.0.38

**Comment by skvark** [comment]
This project dropped Python 2.7 support earlier this year. The notice about this was pinned in this repository since 2018: https://github.com/skvark/opencv-python/issues/152

It's also clearly written in the 4.2.0.34 release notes: https://github.com/skvark/opencv-python/releases/tag/34

It's also written in the README: https://github.com/skvark/opencv-python#supported-python-versions

If you insist on using Python 2.7, then you are stuck with the latest supported release which is 4.2.0.32.

Please update to Python 3.8 and you can enjoy all the latest OpenCV features.
