### ISSUE TITLE
Raspberry pi 

### ISSUE THREAD

**Issue by git-chenjiqing** [skvark/opencv-python#390]
### Expected behaviour

opencv-python-4.4.0.42

### Actual behaviour

I Try python3 setup.py sdist bdist_wheel || true、Here is a list of errors:
running sdist
running generate_source_manifest
fatal: 不是一个 git 仓库（或者任何父目录）：.git
fatal: 不是一个 git 仓库（或者任何父目录）：.git

Since scikit-build could not find MANIFEST.in or MANIFEST, it tried to generate a MANIFEST file automatically, but could not because it could not determine which source files to include.

The command used was "git ls-files"

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/skbuild/command/generate_source_manifest.py", line 57, in run
    subprocess.check_output(['git', 'ls-files', '--recurse-submodules'])
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'ls-files', '--recurse-submodules']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 449, in <module>
    main()
  File "setup.py", line 249, in main
    cmake_source_dir=cmake_source_dir,
  File "/usr/local/lib/python3.7/dist-packages/skbuild/setuptools_wrap.py", line 693, in setup
    return upstream_setup(*args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/dist-packages/skbuild/command/sdist.py", line 63, in run
    self.run_command('generate_source_manifest')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/dist-packages/skbuild/command/generate_source_manifest.py", line 61, in run
    subprocess.check_output(['git', 'ls-files'])
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'ls-files']' returned non-zero exit status 128.
### Steps to reproduce

- python3 setup.py sdist bdist_wheel || true
- raspberry4 
- ARM Cortex-A72
- opencv-python 4.4.0.42

##### Issue submission checklist

 - [ ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [ ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by skvark** [comment]
https://github.com/skvark/opencv-python#manual-builds
