### ISSUE TITLE
ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.

### ISSUE THREAD

**Issue by followertryingtobeprogrammer** [skvark/opencv-python#432]
when built opencv4.4.0, folder 'cv2' had been create in python's site-packages.
my env:
cuda 10.2
python 3.8
vs2017
cmake3.19

```
>>>import cv2
ImportError: DLL load failed while importing cv2 
```
then i used opencv's python_loader
```
>python setup.py install
>python
>>>import cv2
>>>ImportError: DLL load failed while importing cv2 
['', 'D:/CodingEnv/opencv/opencv4.4.0/sources/build/lib/python3/Release', 'D:\\CodingEnv\\python\\python3.8.5\\python38.zip', 'D:\\CodingEnv\\python\\python3.8.5\\DLLs', 'D:\\CodingEnv\\python\\python3.8.5\\lib', 'D:\\CodingEnv\\python\\python3.8.5', 'D:\\CodingEnv\\python\\python3.8.5\\lib\\site-packages', 'd:\\codingenv\\opencv\\opencv4.4.0\\sources\\build\\python_loader']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\CodingEnv\opencv\opencv4.4.0\sources\build\python_loader\cv2\__init__.py", line 96, in <module>
    bootstrap()
  File "D:\CodingEnv\opencv\opencv4.4.0\sources\build\python_loader\cv2\__init__.py", line 86, in bootstrap
    import cv2
  File "D:\CodingEnv\opencv\opencv4.4.0\sources\build\python_loader\cv2\__init__.py", line 96, in <module>
    bootstrap()
  File "D:\CodingEnv\opencv\opencv4.4.0\sources\build\python_loader\cv2\__init__.py", line 23, in bootstrap
    raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.

```

**Comment by followertryingtobeprogrammer** [comment]
![image](https://user-images.githubusercontent.com/45504189/103448079-1a699380-4ccf-11eb-8859-f02d9ccb7a6e.png)

**Comment by skvark** [comment]
Seems that you are not using this repository (`pip install opencv-python`), there is no python_loader here. Please open an issue to the OpenCV repository.

**Comment by mrjeckel** [comment]
Seeing a similar issue when packaging with pyinstaller using opencv-python 46.6.0.66 from pypi. 4.5.5.64 work fine.

```
Traceback (most recent call last):
  File "ftf_app_bambam.py", line 2, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "taskmaster/app_manager.py", line 30, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "hardware/ximea_camera/setup_tools/filter_tuning.py", line 9, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "importlib/__init__.py", line 127, in import_module
    applySysPathWorkaround = True
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "cv2/__init__.py", line 76, in bootstrap
    raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
[11606] Failed to execute script 'ftf_app_bambam' due to unhandled exception!
```
