### ISSUE TITLE
TypeError: _classify_installed_files() got an unexpected keyword argument '_cmake_install_dir'

### ISSUE THREAD

**Issue by wqh17101** [skvark/opencv-python#826]
```
[2023/04/03 14:09:40.468] Traceback (most recent call last):
[2023/04/03 14:09:40.468]   File "/home/aaa/source_code/opencv-python/setup.py", line 711, in <module>
[2023/04/03 14:09:40.468]     main()
[2023/04/03 14:09:40.469]   File "/home/aaa/source_code/opencv-python/setup.py", line 437, in main
[2023/04/03 14:09:40.469]     skbuild.setup(
[2023/04/03 14:09:40.469]   File "/usr/local/python3.9/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 627, in setup
[2023/04/03 14:09:40.469]     _classify_installed_files(cmake_manifest, package_data, package_prefixes,
[2023/04/03 14:09:40.469]   File "/home/aaa/source_code/opencv-python/setup.py", line 651, in _classify_installed_files_override
[2023/04/03 14:09:40.469]     return (cls.wraps._classify_installed_files)(
[2023/04/03 14:09:40.469] TypeError: _classify_installed_files() got an unexpected keyword argument '_cmake_install_dir'
```
opencv-python 4.7.0.72

**Comment by wqh17101** [comment]
skbuild should be >=0.13.2
