### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file while pushing to Cloud Foundry

### ISSUE THREAD

**Issue by songwk** [skvark/opencv-python#851]
### Expected behaviour
Load the opencv and start the python application on the cloud foundry successfully. 
I don't know how to add the opencv to requirements.txt or setup.py for the cloud foundry push. Though it worked on my local docker environment. Could you guide to import and load the opencv while using in Cloud Foundry env?

FROM python:3.9
RUN apt-get update && apt-get install -y python3-opencv
RUN python -m pip install --upgrade pip 
COPY . /app
WORKDIR /app
RUN pip install --trusted-host pypi.python.org -r requirements.txt
RUN python scripts/download_paddleocr_models.py 
ENV PYTHONUNBUFFERED=1
ENV LANG=C.UTF-8
EXPOSE 8080
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8080", "--timeout", "180", "main:app"]

### Actual behaviour
**Failed to start the python app.**

2023-05-26T07:23:55.750+0000 [STG/0] STDOUT Successfully installed Babel-2.12.1 Flask-2.3.2 Flask-Babel-3.1.0 Jinja2-3.1.2 MarkupSafe-2.1.2 Pillow-9.5.0 PyMuPDF-1.20.2 PyWavelets-1.4.1 Werkzeug-2.3.4 aiohttp-3.8.4 aiosignal-1.3.1 anyio-3.6.2 astor-0.8.1 async-timeout-4.0.2 attrdict-2.0.1 attrs-23.1.0 bce-python-sdk-0.8.83 bcrypt-4.0.1 beautifulsoup4-4.12.2 blinker-1.6.2 brotli-1.0.9 cachetools-5.3.0 certifi-2023.5.7 cffi-1.15.1 charset-normalizer-3.1.0 click-8.1.3 contourpy-1.0.7 cryptography-40.0.2 cssselect-1.2.0 cssutils-2.6.0 cycler-0.11.0 cython-0.29.35 decorator-5.1.1 et-xmlfile-1.1.0 fastapi-0.95.2 ffmpy-0.3.0 fire-0.5.0 fonttools-4.39.4 frozenlist-1.3.3 fsspec-2023.5.0 future-0.18.3 gevent-22.10.2 geventhttpclient-2.0.2 gradio-3.11.0 greenlet-2.0.2 grpcio-1.54.2 gunicorn-20.1.0 h11-0.12.0 httpcore-0.15.0 httpx-0.24.1 idna-3.4 imageio-2.29.0 imgaug-0.4.0 itsdangerous-2.1.2 kiwisolver-1.4.4 lazy_loader-0.2 linkify-it-py-2.0.2 lmdb-1.4.1 lxml-4.9.2 markdown-it-py-2.2.0 matplotlib-3.7.1 mdit-py-plugins-0.3.5 mdurl-0.1.2 mpmath-1.3.0 multidict-6.0.4 networkx-3.1 numpy-1.24.3 onnx-1.12.0 **opencv-contrib-python-4.6.0.66 opencv-python-4.6.0.66** openpyxl-3.1.2 opt-einsum-3.3.0 orjson-3.8.14 packaging-23.1 paddle-bfloat-0.1.7 paddle2onnx-1.0.6 paddleocr-2.6.1.3 paddlepaddle-2.4.2 pandas-2.0.1 paramiko-3.2.0 pdf2docx-0.5.6 premailer-3.10.0 protobuf-3.20.0 psutil-5.9.5 pyclipper-1.3.0.post4 pycparser-2.21 pycryptodome-3.18.0 pydantic-1.10.8 pydub-0.25.1 pynacl-1.5.0 pyparsing-3.0.9 python-dateutil-2.8.2 python-docx-0.8.11 python-multipart-0.0.6 python-rapidjson-1.10 pytz-2023.3 pyyaml-6.0 rapidfuzz-3.0.0 rarfile-4.0 requests-2.31.0 scikit-image-0.20.0 scipy-1.10.1 setuptools-67.8.0 shapely-2.0.1 six-1.16.0 sniffio-1.3.0 soupsieve-2.4.1 starlette-0.27.0 sympy-1.12 termcolor-2.3.0 tifffile-2023.4.12 tqdm-4.65.0 tritonclient-2.33.0 typing-extensions-4.6.2 tzdata-2023.3 uc-micro-py-1.0.2 ui5-ocr-app-0.0.1 urllib3-2.0.2 uvicorn-0.22.0 visualdl-2.5.2 websockets-11.0.3 x2paddle-1.4.1 yarl-1.9.2 zope.event-4.6 zope.interface-6.0

2023-05-26T07:33:08.246+0000 [CELL/0] STDOUT Starting health monitoring of container
2023-05-26T07:33:09.440+0000 [APP/PROC/WEB/0] STDERR /home/vcap/deps/0/python/lib/python3.10/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
2023-05-26T07:33:09.440+0000 [APP/PROC/WEB/0] STDERR warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
2023-05-26T07:33:09.460+0000 [APP/PROC/WEB/0] STDERR /home/vcap/deps/0/python/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
2023-05-26T07:33:09.460+0000 [APP/PROC/WEB/0] STDERR Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
2023-05-26T07:33:09.460+0000 [APP/PROC/WEB/0] STDERR declare_namespace(pkg)
2023-05-26T07:33:09.462+0000 [APP/PROC/WEB/0] STDERR /home/vcap/deps/0/python/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
2023-05-26T07:33:09.462+0000 [APP/PROC/WEB/0] STDERR Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
2023-05-26T07:33:09.462+0000 [APP/PROC/WEB/0] STDERR declare_namespace(pkg)
2023-05-26T07:33:09.467+0000 [APP/PROC/WEB/0] STDERR /home/vcap/deps/0/python/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
2023-05-26T07:33:09.467+0000 [APP/PROC/WEB/0] STDERR Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
2023-05-26T07:33:09.467+0000 [APP/PROC/WEB/0] STDERR declare_namespace(pkg)
2023-05-26T07:33:10.284+0000 [APP/PROC/WEB/0] STDERR Traceback (most recent call last):
2023-05-26T07:33:10.284+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/app/main.py", line 3, in <module>
2023-05-26T07:33:10.284+0000 [APP/PROC/WEB/0] STDERR from ocr import MDK_OCR
2023-05-26T07:33:10.284+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/app/ocr.py", line 1, in <module>
2023-05-26T07:33:10.284+0000 [APP/PROC/WEB/0] STDERR from paddleocr import PaddleOCR, draw_ocr
2023-05-26T07:33:10.284+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/site-packages/paddleocr/__init__.py", line 14, in <module>
2023-05-26T07:33:10.284+0000 [APP/PROC/WEB/0] STDERR from .paddleocr import *
2023-05-26T07:33:10.284+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 25, in <module>
2023-05-26T07:33:10.284+0000 [APP/PROC/WEB/0] STDERR import cv2
2023-05-26T07:33:10.284+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
2023-05-26T07:33:10.284+0000 [APP/PROC/WEB/0] STDERR bootstrap()
2023-05-26T07:33:10.284+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
2023-05-26T07:33:10.285+0000 [APP/PROC/WEB/0] STDERR native_module = importlib.import_module("cv2")
2023-05-26T07:33:10.285+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-05-26T07:33:10.285+0000 [APP/PROC/WEB/0] STDERR return _bootstrap._gcd_import(name[level:], package, level)
2023-05-26T07:33:10.285+0000 [APP/PROC/WEB/0] STDERR ImportError: libGL.so.1: cannot open shared object file: No such file or directory
2023-05-26T07:33:10.455+0000 [APP/PROC/WEB/0] STDOUT Exit status 1
2023-05-26T07:33:10.459+0000 [CELL/SSHD/0] STDOUT Exit status 0

**I also tried packaged for cloud, but got the same failure**

2023-05-26T01:14:36.011+0000 [STG/0] STDOUT Installing collected packages: rarfile, pytz, pydub, pyclipper, paddle2onnx, paddle-bfloat, mpmath, lmdb, ffmpy, brotli, websockets, urllib3, uc-micro-py, tzdata, typing-extensions, tqdm, termcolor, sympy, soupsieve, sniffio, six, setuptools, rapidfuzz, pyyaml, python-rapidjson, python-multipart, pyparsing, PyMuPDF, pycryptodome, pycparser, psutil, protobuf, Pillow, packaging, orjson, numpy, networkx, multidict, mdurl, MarkupSafe, lxml, lazy_loader, kiwisolver, itsdangerous, idna, h11, grpcio, greenlet, future, fsspec, frozenlist, fonttools, et-xmlfile, decorator, cython, cycler, cssutils, cssselect, click, charset-normalizer, certifi, cachetools, blinker, bcrypt, Babel, attrs, async-timeout, astor, zope.interface, zope.event, yarl, x2paddle, Werkzeug, uvicorn, tritonclient, tifffile, shapely, scipy, requests, PyWavelets, python-docx, python-dateutil, pydantic, opt-einsum, openpyxl, opencv-python-headless, opencv-python, opencv-contrib-python, onnx, markdown-it-py, linkify-it-py, Jinja2, imageio, gunicorn, fire, contourpy, cffi, beautifulsoup4, bce-python-sdk, attrdict, anyio, aiosignal, starlette, scikit-image, pynacl, premailer, pdf2docx, pandas, paddlepaddle, mdit-py-plugins, matplotlib, httpcore, gevent, Flask, cryptography, aiohttp, paramiko, imgaug, httpx, geventhttpclient, Flask-Babel, fastapi, gradio, visualdl, paddleocr

2023-05-26T01:15:36.368+0000 [STG/0] STDOUT Successfully installed Babel-2.12.1 Flask-2.3.2 Flask-Babel-3.1.0 Jinja2-3.1.2 MarkupSafe-2.1.2 Pillow-9.5.0 PyMuPDF-1.20.2 PyWavelets-1.4.1 Werkzeug-2.3.4 aiohttp-3.8.4 aiosignal-1.3.1 anyio-3.6.2 astor-0.8.1 async-timeout-4.0.2 attrdict-2.0.1 attrs-23.1.0 bce-python-sdk-0.8.83 bcrypt-4.0.1 beautifulsoup4-4.12.2 blinker-1.6.2 brotli-1.0.9 cachetools-5.3.0 certifi-2023.5.7 cffi-1.15.1 charset-normalizer-3.1.0 click-8.1.3 contourpy-1.0.7 cryptography-40.0.2 cssselect-1.2.0 cssutils-2.6.0 cycler-0.11.0 cython-0.29.35 decorator-5.1.1 et-xmlfile-1.1.0 fastapi-0.95.2 ffmpy-0.3.0 fire-0.5.0 fonttools-4.39.4 frozenlist-1.3.3 fsspec-2023.5.0 future-0.18.3 gevent-22.10.2 geventhttpclient-2.0.2 gradio-3.11.0 greenlet-2.0.2 grpcio-1.54.2 gunicorn-20.1.0 h11-0.12.0 httpcore-0.15.0 httpx-0.24.1 idna-3.4 imageio-2.29.0 imgaug-0.4.0 itsdangerous-2.1.2 kiwisolver-1.4.4 lazy_loader-0.2 linkify-it-py-2.0.2 lmdb-1.4.1 lxml-4.9.2 markdown-it-py-2.2.0 matplotlib-3.7.1 mdit-py-plugins-0.3.5 mdurl-0.1.2 mpmath-1.3.0 multidict-6.0.4 networkx-3.1 numpy-1.24.3 onnx-1.12.0 opencv-contrib-python-4.6.0.66 opencv-python-4.6.0.66 opencv-python-headless-4.7.0.72 openpyxl-3.1.2 opt-einsum-3.3.0 orjson-3.8.14 packaging-23.1 paddle-bfloat-0.1.7 paddle2onnx-1.0.6 paddleocr-2.6.1.3 paddlepaddle-2.4.2 pandas-2.0.1 paramiko-3.2.0 pdf2docx-0.5.6 premailer-3.10.0 protobuf-3.20.0 psutil-5.9.5 pyclipper-1.3.0.post4 pycparser-2.21 pycryptodome-3.18.0 pydantic-1.10.8 pydub-0.25.1 pynacl-1.5.0 pyparsing-3.0.9 python-dateutil-2.8.2 python-docx-0.8.11 python-multipart-0.0.6 python-rapidjson-1.10 pytz-2023.3 pyyaml-6.0 rapidfuzz-3.0.0 rarfile-4.0 requests-2.31.0 scikit-image-0.20.0 scipy-1.10.1 setuptools-67.8.0 shapely-2.0.1 six-1.16.0 sniffio-1.3.0 soupsieve-2.4.1 starlette-0.27.0 sympy-1.12 termcolor-2.3.0 tifffile-2023.4.12 tqdm-4.65.0 tritonclient-2.33.0 typing-extensions-4.6.2 tzdata-2023.3 uc-micro-py-1.0.2 urllib3-2.0.2 uvicorn-0.22.0 visualdl-2.5.2 websockets-11.0.3 x2paddle-1.4.1 yarl-1.9.2 zope.event-4.6 zope.interface-6.0

2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR Traceback (most recent call last):
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR worker.init_process()
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR self.load_wsgi()
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR self.wsgi = self.app.wsgi()
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR self.callable = self.load()
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR return self.load_wsgiapp()
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR return util.import_app(self.app_uri)
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR mod = importlib.import_module(module)
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR return _bootstrap._gcd_import(name[level:], package, level)
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/app/main.py", line 3, in <module>
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR from ocr import MDK_OCR
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/app/ocr.py", line 1, in <module>
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR from paddleocr import PaddleOCR, draw_ocr
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/site-packages/paddleocr/__init__.py", line 14, in <module>
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR from .paddleocr import *
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 25, in <module>
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR import cv2
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR bootstrap()
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR native_module = importlib.import_module("cv2")
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR File "/home/vcap/deps/0/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR return _bootstrap._gcd_import(name[level:], package, level)
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR ImportError: libGL.so.1: cannot open shared object file: No such file or directory
2023-05-26T01:26:04.812+0000 [APP/PROC/WEB/0] STDERR [2023-05-26 01:26:04 +0000] [297] [INFO] Worker exiting (pid: 297)
2023-05-26T01:26:04.925+0000 [APP/PROC/WEB/0] STDERR [2023-05-26 01:26:04 +0000] [8] [WARNING] Worker with pid 297 was terminated due to signal 15
2023-05-26T01:26:04.925+0000 [APP/PROC/WEB/0] STDERR [2023-05-26 01:26:04 +0000] [8] [WARNING] Worker with pid 103 was terminated due to signal 15
2023-05-26T01:26:04.925+0000 [APP/PROC/WEB/0] STDERR [2023-05-26 01:26:04 +0000] [8] [WARNING] Worker with pid 102 was terminated due to signal 15
2023-05-26T01:26:04.990+0000 [APP/PROC/WEB/0] STDERR [2023-05-26 01:26:04 +0000] [8] [INFO] Shutting down: Master
2023-05-26T01:26:04.990+0000 [APP/PROC/WEB/0] STDERR [2023-05-26 01:26:04 +0000] [8] [INFO] Reason: Worker failed to boot.
2023-05-26T01:26:05.025+0000 [APP/PROC/WEB/0] STDOUT Exit status 3
2023-05-26T01:26:05.029+0000 [CELL/SSHD/0] STDOUT Exit status 0

### Steps to reproduce
1. cf login
2. copy setup.py and manifest.yml to root folder
3. cf push

manifest.yml
applications:
- name: ui5-ocr-app
  memory: 512M
  disk_quota: 4096M
  instances: 1
  command: python main.py
  buildpacks:
    - python_buildpack

setup.py
from setuptools import setup, find_packages
setup(
    name='ui5-ocr-app',
    version='0.0.1',
    description='UI5 OCR Service for Cloud Foundry',
    author='',
    author_email='',
    packages=find_packages(),
    install_requires=[
        'numpy',
        'opencv-python',
        'paddlepaddle==2.4.2',
        'Flask==2.3.2',
        'paddleocr==2.6.1.3',
        'Pillow==9.5.0',
        'Werkzeug==2.3.4',
        'gunicorn==20.1.0'
    ],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
    ],
    python_requires=">=3.9",
)

- operating system: Cloud Foundry
- architecture (e.g. x86): n/a
- opencv-python version: 4.6.0.66 

##### Issue submission checklist

 - [ ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
 - [ ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x ] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
`apt-get update && apt-get install -y python3-opencv` - this package is built by Linux distro maintainers. We do not manage it.
You need to use -headless versions of the packages, e.g. `opencv-contrib-python-headless`. It's build without UI support and does not have OpenGL dependency.
```
readelf -d ./cv2.abi3.so 

Dynamic section at offset 0x493f000 contains 39 entries:
  Тег                Тип                  Имя/Знач
 0x000000000000000f (RPATH)              Библиотека rpath: [$ORIGIN/../opencv_contrib_python_headless.libs]
 0x0000000000000001 (NEEDED)             Совм. исп. библиотека: [libpng16-57e5e0a0.so.16.37.0]
 0x0000000000000001 (NEEDED)             Совм. исп. библиотека: [libavcodec-16a334ab.so.59.37.100]
 0x0000000000000001 (NEEDED)             Совм. исп. библиотека: [libavformat-e0b1067c.so.59.27.100]
 0x0000000000000001 (NEEDED)             Совм. исп. библиотека: [libavutil-82c407cb.so.57.28.100]
 0x0000000000000001 (NEEDED)             Совм. исп. библиотека: [libswscale-9b504c0d.so.6.7.100]
 0x0000000000000001 (NEEDED)             Совм. исп. библиотека: [libz.so.1]
 0x0000000000000001 (NEEDED)             Совм. исп. библиотека: [libopenblas-r0-f650aae0.3.3.so]
 0x0000000000000001 (NEEDED)             Совм. исп. библиотека: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Совм. исп. библиотека: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Совм. исп. библиотека: [librt.so.1]
 0x0000000000000001 (NEEDED)             Совм. исп. библиотека: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Совм. исп. библиотека: [libm.so.6]
 0x0000000000000001 (NEEDED)             Совм. исп. библиотека: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Совм. исп. библиотека: [libc.so.6]
 0x0000000000000001 (NEEDED)             Совм. исп. библиотека: [ld-linux-x86-64.so.2]
 0x000000000000000c (INIT)               0x223000
 0x000000000000000d (FINI)               0x3811ca4
 0x0000000000000019 (INIT_ARRAY)         0x4816e00
 0x000000000000001b (INIT_ARRAYSZ)       4352 (байт)
 0x000000000000001a (FINI_ARRAY)         0x4817f00
 0x000000000000001c (FINI_ARRAYSZ)       8 (байт)
 0x000000006ffffef5 (GNU_HASH)           0x4b59028
 0x0000000000000005 (STRTAB)             0x4b5e2c0
 0x0000000000000006 (SYMTAB)             0x390
 0x000000000000000a (STRSZ)              16246 (байт)
 0x000000000000000b (SYMENT)             24 (байт)
 0x0000000000000003 (PLTGOT)             0x48b0000
 0x0000000000000002 (PLTRELSZ)           15072 (байт)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x21e5c0
 0x0000000000000007 (RELA)               0x9028
 0x0000000000000008 (RELASZ)             2184600 (байт)
 0x0000000000000009 (RELAENT)            24 (байт)
 0x000000006ffffffe (VERNEED)            0x8d28
 0x000000006fffffff (VERNEEDNUM)         14
 0x000000006ffffff0 (VERSYM)             0x8762
 0x000000006ffffff9 (RELACOUNT)          84215
 0x0000000000000000 (NULL)               0x0
```
