### ISSUE TITLE
ImportError: DLL load failed while importing cv2: The specified module could not be found.

### ISSUE THREAD

**Issue by 11philip22** [skvark/opencv-python#856]
Hi,
I installed opencv-contrib-python 4.7.0.72 using pip for python 3.11.4 on Windows 10 x86-64
But when I run I get this exceptiom `DLL load failed while importing cv2: The specified module could not be found.`

### Expected behaviour

I expect the module to import and not trow an error.

### Actual behaviour

This exception gets trown
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python311\Lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Python311\Lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing cv2: The specified module could not be found.
```

### Steps to reproduce

- example code
`import cv2`
- operating system
Windows 10, i7-12700H with Intel Iris Xe Graphics and a NVIDIA RTX A1000
- architecture (e.g. x86)
x86-64
- opencv-python version
opencv-contrib-python-4.7.0.72

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by GenericAccount2** [comment]
I have exactly this issue. 
Is there a simple way to see which DLL failed to load, that sounds like a natural starting point for investigation.

**Comment by GenericAccount2** [comment]
After some investigation I see it fails on __init__.py in the cv2 folder on the line native_module = importlib.import_module("cv2")
No idea why yet

**Comment by encouver** [comment]
Is there a solution to this?

**Comment by kker4m** [comment]
Same problem, is there a solution ?

**Comment by GenericAccount2** [comment]
The instructions are a little out of date, but I believe they would solve the issue
Go to Windows -> Settings -> Uninstall/Install Apps
Go to Optional Features
Go to Add button
Look for Windows Media Pack

**Comment by aBelnades** [comment]
@GenericAccount2 This was the solution. Thank you.

**Comment by GenericAccount2** [comment]
I think that OpenCV should consider updating their documentation.
This is a frustrating error to encounter, and if documentation is out of date, and cannot be followed, nobody is normally going to self-solve their issue.

**Comment by opencv-alalek** [comment]
No idea which documentation you want to read.

https://pypi.org/project/opencv-python/

> Q: Import fails on Windows: ImportError: DLL load failed: The specified module could not be found.?
> A: If the import fails on Windows, make sure you have [Visual C++ redistributable 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) installed. If you are using older Windows version than Windows 10 and latest system updates are not installed, [Universal C Runtime](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows) might be also required.
> **Windows N and KN editions do not include Media Feature Pack which is required by OpenCV. If you are using Windows N or KN edition, please install also [Windows Media Feature Pack](https://support.microsoft.com/en-us/help/3145500/media-feature-pack-list-for-windows-n-editions).**
> ...

And this is a copy of top level README of this project:

https://github.com/opencv/opencv-python

**Comment by lanfengc** [comment]
In your Python environment, execute this code and install the required packages.
For example, I created a virtual environment with conda,
I executed "conda install numpy protobuf hdf5 cudnn cudatoolkit".
I don't know if "cudnn cudatoolkit" has to be installed. Since I compiled OpenCV with CUDA, I need to install it.

**Comment by dcarrion87** [comment]
Trying to run https://github.com/cudawarped/opencv-python-cuda-wheels on python 3.11 on Windows Server compiled by @cudawarped and getting import DLL error. All DLLs seem to be there. Not an issue when using python 3.7 on the same system.

**Comment by cudawarped** [comment]
> Trying to run https://github.com/cudawarped/opencv-python-cuda-wheels on python 3.11 on Windows Server compiled by @cudawarped and getting import DLL error. All DLLs seem to be there. Not an issue when using python 3.7 on the same system.

This is not an officially supported release.  Please raise an issue on that repo with more details regarding your setup and which wheel you are using and I'll take a look.

**Comment by dcarrion87** [comment]
@cudawarped solved as part of: https://github.com/opencv/opencv-python/issues/955

**Comment by 201811017** [comment]
I have tried the solution of Windows Media pack and still I have the same issue. But i have the following paths in the environment variables:
![image](https://github.com/opencv/opencv-python/assets/151823095/072f8a03-2387-4702-9580-83d29d63af66)

**Comment by cudawarped** [comment]
> I have tried the solution of Windows Media pack and still I have the same issue

Use process monitor to track down the missing dll.  See [ImportError: DLL load failed while importing cv2: The specified module could not be found](https://cudawarped.github.io/opencv-experiments/nbs/ImportError_dll_load_failed_while_importing_cv2.html)

**Comment by jason660519** [comment]
I got the same problem.

**Comment by fluviotect** [comment]
I have the same problem (Python 3.11)

**Comment by cudawarped** [comment]
@jason660519 and @fluviotect when you ran process monitor which dll's couldn't it find?

**Comment by catequalsgood** [comment]
At least for me the issue seems to be `__init__.cp311-win_amd64.pyd` and `__init__.pyd`. For everything else Process Monitor eventually displays a SUCCESS-message. 
I am using Windows 11 Enterprise, OpenCV 4.6.0 and Python 3.11.8. Using 3.10.14 does not change the behaviour.
I tried looking for the Windows Media Pack but is it neither offered as an optional feature nor does it show up as an installed feature. So maybe my issues is something completely different.

**Comment by cudawarped** [comment]
@catequalsgood I am presuming you are using a script to parse the process monitor output which is how you managed to filter it down to only those two entries, making the result extreemly odd.

Specifically I can't understand why python would be outputing an error that it can't find all the dll's when it has found them.

**Comment by catequalsgood** [comment]
I was not using a script but I changed that and looked at the log again. I did indeed miss one. `intl.dll` also never shows SUCCESS.

**Comment by cudawarped** [comment]
You may find it much easier to parse the exported list, see https://forum.opencv.org/t/dll-load-failed-when-importing-a-self-built-cv2-library-in-python/16942/15

**Comment by catequalsgood** [comment]
The output seems equivalent. More DLLs like `VERSION.dll` are returned because only loading `version.dll` is successful. `__init__.cp311-win_amd64.pyd` as well as `__init__.pyd` are of course missing from the output. Leaving only `intl.dll`

**Comment by SubhamBurnwal-BiswaGames** [comment]
this is such a growing issue.. I am unable to import cv2 for days and my whole project is stuck!

**Comment by cudawarped** [comment]
@SubhamBurnwal-BiswaGames Did you build it yourself?  If so did you check for the missing dll using process explorer and if so what was missing?

**Comment by Raknash3** [comment]
I too was facing the same issue. I have python 3.11.7 in my conda env and I used conda to install opencv and I faced the same import error. I reinstalled the Visual C++ redistributables, checked if opencv package was present in anaconda and even then I couldn't solve the issue. Then I noticed that conda by default installs opencv 4.7 and the lastest version was opencv 4.9. So I used pip to install the latest release of opencv 4.8.1.78 and now I can import the cv2 module successfully.

**Comment by allweatherbiker** [comment]
I feel, that I find a quick and dirty work around with a very long warm up time. 
Solution was, to copie all the exe and dlls's from \opencv-4.6.0-py311h5d08a89_5\Library\bin to opencv-4.6.0-py311h5d08a89_5\Lib\site-packages

I did find out the search path for the missing dll's using Process Monitor  [https://learn.microsoft.com/en-us/sysinternals/downloads/procmon](url)
The used Filters in the Process Monitor tool are: 
- Process Name is Python.exe
- Operation is CreateFile
- Result is not SUCCESS
- Path contains pkgs (I used Anaconda with Spyder, where the directory pkgs used for all the packages.)

 The day before I tryed latest version of opencv and Anaconda crashed, due to qt errors.

**Comment by quyq** [comment]
For me, gstream runtime dll are not in site-packages\cv2 folder. I'm using the way mentioned at [here:](http://dencode.blogspot.com/2024/06/program-d-link-dcs-5010l-part-2.html), i.e. add following before import cv2:
import os
gst_root = os.getenv('GSTREAMER_1_0_ROOT_MSVC_X86_64', 'C:/gstreamer/1.0/msvc_x86_64/')
os.add_dll_directory(gst_root+'bin')
import cv2

**Comment by JLin-45655** [comment]
> I too was facing the same issue. I have python 3.11.7 in my conda env and I used conda to install opencv and I faced the same import error. I reinstalled the Visual C++ redistributables, checked if opencv package was present in anaconda and even then I couldn't solve the issue. Then I noticed that conda by default installs opencv 4.7 and the lastest version was opencv 4.9. So I used pip to install the latest release of opencv 4.8.1.78 and now I can import the cv2 module successfully.

I used Anaconda Navigator to install opencv and got version 4.6.6. Then I had this "DLL load failed while importing cv2" issue. I tried to use "Process Monitor" suggested by other link and found that "intl.dll" was not found. After seeing Raknash3's comment, I removed the opencv with Anaconda Navigator and tried "conda install -c conda-forge open.cv" and had 4.7.0 installed. Now it works. Thanks.

**Comment by sina-razaghi** [comment]
encountered this error on Windows 11 Enterprise N. To fix it, I installed the Media Feature Pack by going to Settings > System > Optional Features > Add an Optional Feature. If the issue persists after installing the Media Feature Pack, try reinstalling OpenCV."

**Comment by SeaKamil** [comment]
I solved a similar problem as follows. 
I hope it helps.

# Directory containing OpenCV DLL files
import os
opencv_dll_path = r"C:\vcpkg\installed\x64-windows\bin"

# Add to system DLL load path
os.add_dll_directory(opencv_dll_path)

import cv2
# Test the OpenCV module
print(cv2.getBuildInformation())

**Comment by SeaKamil** [comment]
I solved a similar problem as follows. I hope it helps.

Example testing.py file
# Directory containing OpenCV DLL files
# Add to system DLL load path
import os
opencv_dll_path = r"C:\vcpkg\installed\x64-windows\bin"
os.add_dll_directory(opencv_dll_path)

# Test the OpenCV module
import cv2
print(cv2.getBuildInformation())

**Comment by SeaKamil** [comment]
I solved a similar problem as follows. I hope it helps.

# Directory containing OpenCV DLL files
# Add to system DLL load path
# Test the OpenCV module

Example testing.py file

import os
opencv_dll_path = r"C:\vcpkg\installed\x64-windows\bin"
os.add_dll_directory(opencv_dll_path)
import cv2
print(cv2.getBuildInformation())

**Comment by SeaKamil** [comment]
I solved a similar problem as follows. I hope it helps.

#opencv_dll_path    : Directory containing OpenCV DLL files
# add_dll_directory  : Add to system DLL load path
# Test the OpenCV module

Example testing.py file

import os
opencv_dll_path = r"C:\vcpkg\installed\x64-windows\bin"
os.add_dll_directory(opencv_dll_path)
import cv2
print(cv2.getBuildInformation())

**Comment by SeaKamil** [comment]
I solved a similar problem as follows. I hope it helps.

# opencv_dll_path    : Directory containing OpenCV DLL files
# add_dll_directory  : Add to system DLL load path
# Test the OpenCV module

Example testing.py file

import os
opencv_dll_path = r"C:\vcpkg\installed\x64-windows\bin"
os.add_dll_directory(opencv_dll_path)
import cv2
print(cv2.getBuildInformation())

**Comment by SeaKamil** [comment]
I solved a similar problem as follows. I hope it helps.

**opencv_dll_path    :** Directory containing OpenCV DLL files
**add_dll_directory  :** Add to system DLL load path

Test the OpenCV module

**Example testing.py file**

import os
opencv_dll_path = r"C:\vcpkg\installed\x64-windows\bin"
os.add_dll_directory(opencv_dll_path)
import cv2
print(cv2.getBuildInformation())

**Comment by SeaKamil** [comment]
I solved a similar problem as follows. I hope it helps.

**opencv_dll_path	:** Address where opencv_worldXXX.dll is located	
**add_dll_directory	:** Add to system DLL load path

Test the OpenCV module

**Example testing.py file**

import os
opencv_dll_path = r"C:\vcpkg\installed\x64-windows\bin"
os.add_dll_directory(opencv_dll_path)
import cv2
print(cv2.getBuildInformation())

**Comment by King-Sager2333** [comment]
i did these and solved this problem:

remove all opencv packages and install opencv-python

!!!just use in python programs!!!

**Comment by ALfuhrmann** [comment]
EDIT: [This fixed it for me](https://github.com/opencv/opencv-python/issues/955#issuecomment-1945537519). Seems the DLL search path behavior in Python changed. I was missing
`os.add_dll_directory(r"C:\Qt\5.15.2\msvc2019_64\bin")`
even though it was in my system PATH.

--------------------------------------------------------------------------------------------------------
Same error, with own build of 4.12.0-dev:
```
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import cv2
  File "C:\Users\vrmun\AppData\Roaming\Python\Python313\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
    ~~~~~~~~~^^
  File "C:\Users\vrmun\AppData\Roaming\Python\Python313\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "C:\Program Files\Python313\Lib\importlib\__init__.py", line 91, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
```

process monitor shows opening an "unknown" file:

```
8:50:09.1108530 AM	python.exe	46152	CloseFile	C:\Program Files\Python313\Lib\importlib\__init__.py	SUCCESS	
8:50:09.1110156 AM	python.exe	46152	CreateFile	C:\_<redacted>_\OpenCV\build\install\x64\vc17\bin\<unknown>	NAME INVALID	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a
```

I am trying to find out where the "\<unknown\>" comes from, but so far no luck.
