### ISSUE TITLE
Bad CRC-32 while installing using pip

### ISSUE THREAD

**Issue by Sourabh-ALTEN** [skvark/opencv-python#889]
Hello,

I am trying to install `opencv-python (4.8.0.74)` on my `aarch64` embedded platform. But it is giving me
`zipfile.BadZipFile: Bad CRC-32 for file 'cv2/cv2.abi3.so'` error.
The GNU/Linux system is Buildroot based and has python version `3.10.4` and pip version `23.2.1`

`pip3 install opencv-python==4.8.0.74 --no-cache-dir`

Log:

```
Collecting opencv-python==4.8.0.74
  Obtaining dependency information for opencv-python==4.8.0.74 from https://files.pythonhosted.org/packages/96/7b/9b3a72a6afa0f98035db324966404f2471489068617e2a781ace121f9615/opencv_python-4.8.0.74-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
  Downloading opencv_python-4.8.0.74-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.21.2 in /usr/lib/python3.10/site-packages (from opencv-python==4.8.0.74) (1.25.2)
Downloading opencv_python-4.8.0.74-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (41.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.0/41.0 MB 11.4 MB/s eta 0:00:00
Installing collected packages: opencv-python
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 452, in run
    installed = install_given_reqs(
  File "/usr/lib/python3.10/site-packages/pip/_internal/req/__init__.py", line 72, in install_given_reqs
    requirement.install(
  File "/usr/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 807, in install
    install_wheel(
  File "/usr/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 731, in install_wheel
    _install_wheel(
  File "/usr/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 591, in _install_wheel
    file.save()
  File "/usr/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 390, in save
    shutil.copyfileobj(f, dest)
  File "/usr/lib/python3.10/shutil.py", line 195, in copyfileobj
  File "/usr/lib/python3.10/zipfile.py", line 925, in read
  File "/usr/lib/python3.10/zipfile.py", line 1015, in _read1
  File "/usr/lib/python3.10/zipfile.py", line 943, in _update_crc
zipfile.BadZipFile: Bad CRC-32 for file 'cv2/cv2.abi3.so'
```

I have tried below things:

1. `pip cache purge`
2. Also tried installing `opencv-contrib-python` but same error
3. `pip download opencv-python==4.8.0.74` and `pip3 install opencv_python-4.8.0.74-cp37-abi3-manylinux_2_17_aarch64.many
linux2014_aarch64.whl` 

Embedded board has good network connection and sufficient disk space. 

Can anyone please let me know what is the issue here and how to resolve it?

Thanks in advance.

**Comment by asmorkalov** [comment]
Most probably your wheel file is corrupted. The issue is not visible on my side.
