### ISSUE TITLE
Python wheel fails to build with enabled OpenVINO backend

### ISSUE THREAD

**Issue by asutic** [skvark/opencv-python#893]
### Expected behavior

I'm following the instruction at https://github.com/opencv/opencv-python#manual-builds to build a custom version of OpenCV 4.8.0 with support for the OpenVINO inference backend.

### Actual behavior

The compilation throws an error. When OpenVINO is not enabled in the same environment, code compilation proceeds without CMake issues. Note that in the CMake command, we indeed see WITH_INF_ENGINE listed twice. But I'm unsure if that is causing issues.

```
CMake Error: install(EXPORT "OpenCVModules" ...) includes target "ocv.3rdparty.openvino" more than once in the export set.
CMake Error in CMakeLists.txt:
  given target "ocv.3rdparty.openvino" more than once.


CMake Generate step failed.  Build files cannot be regenerated correctly.
Traceback (most recent call last):
  File "/home/ci/.local/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 666, in setup
    env = cmkr.configure(
  File "/home/ci/.local/lib/python3.10/site-packages/skbuild/cmaker.py", line 357, in configure
    raise SKBuildError(msg)

An error occurred while configuring with CMake.
  Command:
    /usr/local/bin/cmake /home/ci/opencv-python/opencv -G 'Unix Makefiles' --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/home/ci/opencv-python/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.12 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/ci/.local/lib/python3.10/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/local/bin/python3.10 -DPYTHON_INCLUDE_DIR:PATH=/opt/_internal/cpython-3.10.12/include/python3.10 -DPython_EXECUTABLE:PATH=/usr/local/bin/python3.10 -DPython_ROOT_DIR:PATH=/opt/_internal/cpython-3.10.12 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/opt/_internal/cpython-3.10.12/include/python3.10 -DPython_NumPy_INCLUDE_DIRS:PATH=/home/ci/.local/lib/python3.10/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/usr/local/bin/python3.10 -DPython3_ROOT_DIR:PATH=/opt/_internal/cpython-3.10.12 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/opt/_internal/cpython-3.10.12/include/python3.10 -DPython3_NumPy_INCLUDE_DIRS:PATH=/home/ci/.local/lib/python3.10/site-packages/numpy/core/include -DWITH_INF_ENGINE=ON -DPYTHON3_EXECUTABLE=/usr/local/bin/python3.10 -DPYTHON_DEFAULT_EXECUTABLE=/usr/local/bin/python3.10 -DPYTHON3_INCLUDE_DIR=/opt/_internal/cpython-3.10.12/include/python3.10 -DPYTHON3_LIBRARY=libpython3.10m.a -DBUILD_opencv_python3=ON -DBUILD_opencv_python2=OFF -DBUILD_opencv_java=OFF -DOPENCV_PYTHON3_INSTALL_PATH=python -DINSTALL_CREATE_DISTRIB=ON -DBUILD_opencv_apps=OFF -DBUILD_opencv_freetype=OFF -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_DOCS=OFF -DPYTHON3_LIMITED_API=ON -DBUILD_OPENEXR=ON -DWITH_WIN32UI=OFF -DWITH_QT=OFF -DWITH_GTK=OFF -DCMAKE_BUILD_TYPE:STRING=Release -DWITH_INF_ENGINE=ON
  Source directory:
    /home/ci/opencv-python/opencv
  Working directory:
    /home/ci/opencv-python/_skbuild/linux-x86_64-3.10/cmake-build
Please see CMake's output for more information.
```

### Steps to reproduce

Here is the list of commands to reproduce the issue:

```
docker run -it quay.io/opencv-ci/opencv-python-manylinux2014-x86-64:20230628

cd /home/ci

python3.10 -m pip install --upgrade pip
python3.10 -m pip install scikit-build

curl -L https://storage.openvinotoolkit.org/repositories/openvino/packages/2023.0.1/linux/l_openvino_toolkit_ubuntu20_2023.0.1.11005.fa1c41994f3_x86_64.tgz --output openvino_2023.0.1.tgz
tar -xf openvino_2023.0.1.tgz
mv l_openvino_toolkit_ubuntu20_2023.0.1.11005.fa1c41994f3_x86_64 openvino_2023.0.1
source /home/ci/openvino_2023.0.1/setupvars.sh 

export ENABLE_HEADLESS=1
export CMAKE_ARGS="-DWITH_INF_ENGINE=ON"

git clone --recursive https://github.com/opencv/opencv-python.git

cd opencv-python
python3.10 -m pip wheel . --verbose   # OR python3.10 setup.py bdist_wheel
```

##### Issue submission checklist

 - [X] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
 - [X] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
 - [X] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [X] I'm using the latest version of ``opencv-python``

**Comment by asutic** [comment]
The issue is related to CMake options. WITH_INF_ENGINE is deprecated (and broken?). The new option to enable OpenVINO is WITH_OPENVINO.

**Comment by asutic** [comment]
I'm reopening the issue. WITH_OPENVINO didn't actually help and the issue persists even with this flag.

**Comment by opencv-alalek** [comment]
There is fix in upstream for that (~2 months ago): https://github.com/opencv/opencv/pull/23963

**Comment by asutic** [comment]
Thanks, opencv upgrade solves the issue.
