### ISSUE TITLE
cv2/cv2.abi3.so, 2): Library not loaded: /usr/local/opt/libunistring/lib/libunistring.2.dylib   Referenced from: /usr/local/opt/gnutls/lib/libgnutls.30.dylib

### ISSUE THREAD

**Issue by 1769782410** [skvark/opencv-python#996]
### Expected behaviour

I am using yolov8 pip install ultralytics then running

### Actual behaviour

`Traceback (most recent call last):
  File "/Users/cs/project/yolov8-cs/1.py", line 1, in <module>
    import cv2
  File "/Users/cs/.pyenv/versions/yolo_venv/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/Users/cs/.pyenv/versions/yolo_venv/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/Users/cs/.pyenv/versions/3.10.4/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/Users/cs/.pyenv/versions/3.10.4/envs/yolo_venv/lib/python3.10/site-packages/cv2/cv2.abi3.so, 2): Library not loaded: /usr/local/opt/libunistring/lib/libunistring.2.dylib
  Referenced from: /usr/local/opt/gnutls/lib/libgnutls.30.dylib
  Reason: image not found`

### Steps to reproduce

- example code：import cv2
- operating system  macos 10.15.7 (19H1615)
- architecture (x64)
- opencv-python version  ：Probably up to date, as it uses pip install ultralytics directly

##### Issue submission checklist

 - [ ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [ ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by 1769782410** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8168#issuecomment-1495988226

I used the above link to solve the problem because the version is too high

1. ultralytics  
opencv-python == 4.6.0.66 

1. pip install --upgrade "protobuf<=3.20.2"
